/*
Copyright 2021 The Vitess Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package psql

import (
	"fmt"
	"strings"

	"github.com/usalko/sent/internal/sql_parser/cache"
)

// keywords is a table of psql keywords that fall into two categories:
// 1) keywords considered reserved by PostgresQL
// 2) keywords for us to handle specially in psql.y
//
// Those marked as UNUSED are likely reserved keywords. We add them here so that
// when rewriting queries we can properly backtick quote them so they don't cause issues
//
// NOTE: If you add new keywords, add them also to the reserved_keywords or
// non_reserved_keywords grammar in sql.y -- this will allow the keyword to be used
// in identifiers. See the docs for each grammar to determine which one to put it into.
var keywords = []cache.Keyword{
	{Name: "_armscii8", Id: UNDERSCORE_ARMSCII8},
	{Name: "_ascii", Id: UNDERSCORE_ASCII},
	{Name: "_big5", Id: UNDERSCORE_BIG5},
	{Name: "_binary", Id: UNDERSCORE_BINARY},
	{Name: "_cp1250", Id: UNDERSCORE_CP1250},
	{Name: "_cp1251", Id: UNDERSCORE_CP1251},
	{Name: "_cp1256", Id: UNDERSCORE_CP1256},
	{Name: "_cp1257", Id: UNDERSCORE_CP1257},
	{Name: "_cp850", Id: UNDERSCORE_CP850},
	{Name: "_cp852", Id: UNDERSCORE_CP852},
	{Name: "_cp866", Id: UNDERSCORE_CP866},
	{Name: "_cp932", Id: UNDERSCORE_CP932},
	{Name: "_dec8", Id: UNDERSCORE_DEC8},
	{Name: "_eucjpms", Id: UNDERSCORE_EUCJPMS},
	{Name: "_euckr", Id: UNDERSCORE_EUCKR},
	{Name: "_gb18030", Id: UNDERSCORE_GB18030},
	{Name: "_gb2312", Id: UNDERSCORE_GB2312},
	{Name: "_gbk", Id: UNDERSCORE_GBK},
	{Name: "_geostd8", Id: UNDERSCORE_GEOSTD8},
	{Name: "_greek", Id: UNDERSCORE_GREEK},
	{Name: "_hebrew", Id: UNDERSCORE_HEBREW},
	{Name: "_hp8", Id: UNDERSCORE_HP8},
	{Name: "_keybcs2", Id: UNDERSCORE_KEYBCS2},
	{Name: "_koi8r", Id: UNDERSCORE_KOI8R},
	{Name: "_koi8u", Id: UNDERSCORE_KOI8U},
	{Name: "_latin1", Id: UNDERSCORE_LATIN1},
	{Name: "_latin2", Id: UNDERSCORE_LATIN2},
	{Name: "_latin5", Id: UNDERSCORE_LATIN5},
	{Name: "_latin7", Id: UNDERSCORE_LATIN7},
	{Name: "_macce", Id: UNDERSCORE_MACCE},
	{Name: "_macroman", Id: UNDERSCORE_MACROMAN},
	{Name: "_sjis", Id: UNDERSCORE_SJIS},
	{Name: "_swe7", Id: UNDERSCORE_SWE7},
	{Name: "_tis620", Id: UNDERSCORE_TIS620},
	{Name: "_ucs2", Id: UNDERSCORE_UCS2},
	{Name: "_ujis", Id: UNDERSCORE_UJIS},
	{Name: "_utf16", Id: UNDERSCORE_UTF16},
	{Name: "_utf16le", Id: UNDERSCORE_UTF16LE},
	{Name: "_utf32", Id: UNDERSCORE_UTF32},
	{Name: "_utf8", Id: UNDERSCORE_UTF8},
	{Name: "_utf8mb4", Id: UNDERSCORE_UTF8MB4},
	{Name: "_utf8mb3", Id: UNDERSCORE_UTF8MB3},
	{Name: "accessible", Id: UNUSED},
	{Name: "action", Id: ACTION},
	{Name: "add", Id: ADD},
	{Name: "after", Id: AFTER},
	{Name: "against", Id: AGAINST},
	{Name: "algorithm", Id: ALGORITHM},
	{Name: "all", Id: ALL},
	{Name: "alter", Id: ALTER},
	{Name: "always", Id: ALWAYS},
	{Name: "analyze", Id: ANALYZE},
	{Name: "and", Id: AND},
	{Name: "as", Id: AS},
	{Name: "asc", Id: ASC},
	{Name: "ascii", Id: ASCII},
	{Name: "asensitive", Id: UNUSED},
	{Name: "auto_increment", Id: AUTO_INCREMENT},
	{Name: "autoextend_size", Id: AUTOEXTEND_SIZE},
	{Name: "avg_row_length", Id: AVG_ROW_LENGTH},
	{Name: "before", Id: UNUSED},
	{Name: "begin", Id: BEGIN},
	{Name: "between", Id: BETWEEN},
	{Name: "bigint", Id: BIGINT},
	{Name: "binary", Id: BINARY},
	{Name: "bit", Id: BIT},
	{Name: "blob", Id: BLOB},
	{Name: "bool", Id: BOOL},
	{Name: "boolean", Id: BOOLEAN},
	{Name: "both", Id: BOTH},
	{Name: "by", Id: BY},
	{Name: "byte", Id: BYTE},
	{Name: "call", Id: CALL},
	{Name: "cancel", Id: CANCEL},
	{Name: "cascade", Id: CASCADE},
	{Name: "cascaded", Id: CASCADED},
	{Name: "case", Id: CASE},
	{Name: "cast", Id: CAST},
	{Name: "channel", Id: CHANNEL},
	{Name: "change", Id: CHANGE},
	{Name: "char", Id: CHAR},
	{Name: "character", Id: CHARACTER},
	{Name: "charset", Id: CHARSET},
	{Name: "check", Id: CHECK},
	{Name: "checksum", Id: CHECKSUM},
	{Name: "cleanup", Id: CLEANUP},
	{Name: "coalesce", Id: COALESCE},
	{Name: "code", Id: CODE},
	{Name: "collate", Id: COLLATE},
	{Name: "collation", Id: COLLATION},
	{Name: "column", Id: COLUMN},
	{Name: "column_format", Id: COLUMN_FORMAT},
	{Name: "columns", Id: COLUMNS},
	{Name: "comment", Id: COMMENT_KEYWORD},
	{Name: "committed", Id: COMMITTED},
	{Name: "commit", Id: COMMIT},
	{Name: "compact", Id: COMPACT},
	{Name: "complete", Id: COMPLETE},
	{Name: "compressed", Id: COMPRESSED},
	{Name: "compression", Id: COMPRESSION},
	{Name: "condition", Id: UNUSED},
	{Name: "connection", Id: CONNECTION},
	{Name: "constraint", Id: CONSTRAINT},
	{Name: "continue", Id: UNUSED},
	{Name: "convert", Id: CONVERT},
	{Name: "copy", Id: COPY},
	{Name: "cume_dist", Id: UNUSED},
	{Name: "substr", Id: SUBSTRING},
	{Name: "subpartition", Id: SUBPARTITION},
	{Name: "subpartitions", Id: SUBPARTITIONS},
	{Name: "substring", Id: SUBSTRING},
	{Name: "srid", Id: SRID},
	{Name: "create", Id: CREATE},
	{Name: "cross", Id: CROSS},
	{Name: "csv", Id: CSV},
	{Name: "current_date", Id: CURRENT_DATE},
	{Name: "current_time", Id: CURRENT_TIME},
	{Name: "current_timestamp", Id: CURRENT_TIMESTAMP},
	{Name: "current_user", Id: CURRENT_USER},
	{Name: "cursor", Id: UNUSED},
	{Name: "data", Id: DATA},
	{Name: "database", Id: DATABASE},
	{Name: "databases", Id: DATABASES},
	{Name: "day", Id: DAY},
	{Name: "day_hour", Id: DAY_HOUR},
	{Name: "day_microsecond", Id: DAY_MICROSECOND},
	{Name: "day_minute", Id: DAY_MINUTE},
	{Name: "day_second", Id: DAY_SECOND},
	{Name: "date", Id: DATE},
	{Name: "datetime", Id: DATETIME},
	{Name: "deallocate", Id: DEALLOCATE},
	{Name: "dec", Id: UNUSED},
	{Name: "decimal", Id: DECIMAL_TYPE},
	{Name: "declare", Id: UNUSED},
	{Name: "default", Id: DEFAULT},
	{Name: "definer", Id: DEFINER},
	{Name: "delay_key_write", Id: DELAY_KEY_WRITE},
	{Name: "delayed", Id: UNUSED},
	{Name: "delete", Id: DELETE},
	{Name: "dense_rank", Id: UNUSED},
	{Name: "desc", Id: DESC},
	{Name: "describe", Id: DESCRIBE},
	{Name: "deterministic", Id: UNUSED},
	{Name: "directory", Id: DIRECTORY},
	{Name: "disable", Id: DISABLE},
	{Name: "discard", Id: DISCARD},
	{Name: "disk", Id: DISK},
	{Name: "distinct", Id: DISTINCT},
	{Name: "distinctrow", Id: DISTINCTROW},
	{Name: "div", Id: DIV},
	{Name: "double", Id: DOUBLE},
	{Name: "do", Id: DO},
	{Name: "drop", Id: DROP},
	{Name: "dumpfile", Id: DUMPFILE},
	{Name: "duplicate", Id: DUPLICATE},
	{Name: "dynamic", Id: DYNAMIC},
	{Name: "each", Id: UNUSED},
	{Name: "else", Id: ELSE},
	{Name: "elseif", Id: UNUSED},
	{Name: "empty", Id: EMPTY},
	{Name: "enable", Id: ENABLE},
	{Name: "enclosed", Id: ENCLOSED},
	{Name: "encryption", Id: ENCRYPTION},
	{Name: "end", Id: END},
	{Name: "enforced", Id: ENFORCED},
	{Name: "engine", Id: ENGINE},
	{Name: "engine_attribute", Id: ENGINE_ATTRIBUTE},
	{Name: "engines", Id: ENGINES},
	{Name: "enum", Id: ENUM},
	{Name: "error", Id: ERROR},
	{Name: "escape", Id: ESCAPE},
	{Name: "escaped", Id: ESCAPED},
	{Name: "event", Id: EVENT},
	{Name: "exchange", Id: EXCHANGE},
	{Name: "exclusive", Id: EXCLUSIVE},
	{Name: "execute", Id: EXECUTE},
	{Name: "exists", Id: EXISTS},
	{Name: "exit", Id: UNUSED},
	{Name: "explain", Id: EXPLAIN},
	{Name: "expansion", Id: EXPANSION},
	{Name: "expire", Id: EXPIRE},
	{Name: "export", Id: EXPORT},
	{Name: "extended", Id: EXTENDED},
	{Name: "extract", Id: EXTRACT},
	{Name: "false", Id: FALSE},
	{Name: "fetch", Id: UNUSED},
	{Name: "fields", Id: FIELDS},
	{Name: "first", Id: FIRST},
	{Name: "first_value", Id: UNUSED},
	{Name: "fixed", Id: FIXED},
	{Name: "float", Id: FLOAT_TYPE},
	{Name: "float4", Id: UNUSED},
	{Name: "float8", Id: UNUSED},
	{Name: "flush", Id: FLUSH},
	{Name: "for", Id: FOR},
	{Name: "force", Id: FORCE},
	{Name: "foreign", Id: FOREIGN},
	{Name: "format", Id: FORMAT},
	{Name: "from", Id: FROM},
	{Name: "full", Id: FULL},
	{Name: "fulltext", Id: FULLTEXT},
	{Name: "function", Id: FUNCTION},
	{Name: "general", Id: GENERAL},
	{Name: "generated", Id: GENERATED},
	{Name: "geometry", Id: GEOMETRY},
	{Name: "geometrycollection", Id: GEOMETRYCOLLECTION},
	{Name: "get", Id: UNUSED},
	{Name: "global", Id: GLOBAL},
	{Name: "gtid_executed", Id: GTID_EXECUTED},
	{Name: "grant", Id: UNUSED},
	{Name: "group", Id: GROUP},
	{Name: "grouping", Id: UNUSED},
	{Name: "groups", Id: UNUSED},
	{Name: "group_concat", Id: GROUP_CONCAT},
	{Name: "hash", Id: HASH},
	{Name: "having", Id: HAVING},
	{Name: "header", Id: HEADER},
	{Name: "high_priority", Id: UNUSED},
	{Name: "hosts", Id: HOSTS},
	{Name: "hour", Id: HOUR},
	{Name: "hour_microsecond", Id: HOUR_MICROSECOND},
	{Name: "hour_minute", Id: HOUR_MINUTE},
	{Name: "hour_second", Id: HOUR_SECOND},
	{Name: "if", Id: IF},
	{Name: "ignore", Id: IGNORE},
	{Name: "import", Id: IMPORT},
	{Name: "in", Id: IN},
	{Name: "index", Id: INDEX},
	{Name: "indexes", Id: INDEXES},
	{Name: "infile", Id: UNUSED},
	{Name: "inout", Id: UNUSED},
	{Name: "inner", Id: INNER},
	{Name: "inplace", Id: INPLACE},
	{Name: "insensitive", Id: UNUSED},
	{Name: "insert", Id: INSERT},
	{Name: "insert_method", Id: INSERT_METHOD},
	{Name: "instant", Id: INSTANT},
	{Name: "invisible", Id: INVISIBLE},
	{Name: "int", Id: INT},
	{Name: "int1", Id: UNUSED},
	{Name: "int2", Id: UNUSED},
	{Name: "int3", Id: UNUSED},
	{Name: "int4", Id: UNUSED},
	{Name: "int8", Id: UNUSED},
	{Name: "integer", Id: INTEGER},
	{Name: "interval", Id: INTERVAL},
	{Name: "into", Id: INTO},
	{Name: "io_after_gtids", Id: UNUSED},
	{Name: "is", Id: IS},
	{Name: "isolation", Id: ISOLATION},
	{Name: "iterate", Id: UNUSED},
	{Name: "invoker", Id: INVOKER},
	{Name: "join", Id: JOIN},
	{Name: "json", Id: JSON},
	{Name: "json_array", Id: JSON_ARRAY},
	{Name: "json_array_append", Id: JSON_ARRAY_APPEND},
	{Name: "json_array_insert", Id: JSON_ARRAY_INSERT},
	{Name: "json_contains", Id: JSON_CONTAINS},
	{Name: "json_contains_path", Id: JSON_CONTAINS_PATH},
	{Name: "json_depth", Id: JSON_DEPTH},
	{Name: "json_extract", Id: JSON_EXTRACT},
	{Name: "json_insert", Id: JSON_INSERT},
	{Name: "json_length", Id: JSON_LENGTH},
	{Name: "json_keys", Id: JSON_KEYS},
	{Name: "json_merge", Id: JSON_MERGE},
	{Name: "json_merge_patch", Id: JSON_MERGE_PATCH},
	{Name: "json_merge_preserve", Id: JSON_MERGE_PRESERVE},
	{Name: "json_object", Id: JSON_OBJECT},
	{Name: "json_overlaps", Id: JSON_OVERLAPS},
	{Name: "json_pretty", Id: JSON_PRETTY},
	{Name: "json_remove", Id: JSON_REMOVE},
	{Name: "json_replace", Id: JSON_REPLACE},
	{Name: "json_search", Id: JSON_SEARCH},
	{Name: "json_schema_valid", Id: JSON_SCHEMA_VALID},
	{Name: "json_schema_validation_report", Id: JSON_SCHEMA_VALIDATION_REPORT},
	{Name: "json_set", Id: JSON_SET},
	{Name: "json_storage_free", Id: JSON_STORAGE_FREE},
	{Name: "json_storage_size", Id: JSON_STORAGE_SIZE},
	{Name: "json_quote", Id: JSON_QUOTE},
	{Name: "json_table", Id: JSON_TABLE},
	{Name: "json_type", Id: JSON_TYPE},
	{Name: "json_value", Id: JSON_VALUE},
	{Name: "json_valid", Id: JSON_VALID},
	{Name: "json_unquote", Id: JSON_UNQUOTE},
	{Name: "key", Id: KEY},
	{Name: "keys", Id: KEYS},
	{Name: "keyspaces", Id: KEYSPACES},
	{Name: "key_block_size", Id: KEY_BLOCK_SIZE},
	{Name: "kill", Id: UNUSED},
	{Name: "lag", Id: UNUSED},
	{Name: "language", Id: LANGUAGE},
	{Name: "last", Id: LAST},
	{Name: "last_value", Id: UNUSED},
	{Name: "last_insert_id", Id: LAST_INSERT_ID},
	{Name: "lateral", Id: LATERAL},
	{Name: "lead", Id: UNUSED},
	{Name: "leading", Id: LEADING},
	{Name: "leave", Id: UNUSED},
	{Name: "left", Id: LEFT},
	{Name: "less", Id: LESS},
	{Name: "level", Id: LEVEL},
	{Name: "like", Id: LIKE},
	{Name: "limit", Id: LIMIT},
	{Name: "linear", Id: LINEAR},
	{Name: "lines", Id: LINES},
	{Name: "linestring", Id: LINESTRING},
	{Name: "list", Id: LIST},
	{Name: "load", Id: LOAD},
	{Name: "local", Id: LOCAL},
	{Name: "localtime", Id: LOCALTIME},
	{Name: "localtimestamp", Id: LOCALTIMESTAMP},
	{Name: "lock", Id: LOCK},
	{Name: "logs", Id: LOGS},
	{Name: "long", Id: UNUSED},
	{Name: "longblob", Id: LONGBLOB},
	{Name: "longtext", Id: LONGTEXT},
	{Name: "loop", Id: UNUSED},
	{Name: "low_priority", Id: LOW_PRIORITY},
	{Name: "ltrim", Id: LTRIM},
	{Name: "manifest", Id: MANIFEST},
	{Name: "master_bind", Id: UNUSED},
	{Name: "match", Id: MATCH},
	{Name: "max_rows", Id: MAX_ROWS},
	{Name: "maxvalue", Id: MAXVALUE},
	{Name: "mediumblob", Id: MEDIUMBLOB},
	{Name: "mediumint", Id: MEDIUMINT},
	{Name: "mediumtext", Id: MEDIUMTEXT},
	{Name: "memory", Id: MEMORY},
	{Name: "member", Id: MEMBER},
	{Name: "merge", Id: MERGE},
	{Name: "microsecond", Id: MICROSECOND},
	{Name: "middleint", Id: UNUSED},
	{Name: "min_rows", Id: MIN_ROWS},
	{Name: "minute", Id: MINUTE},
	{Name: "minute_microsecond", Id: MINUTE_MICROSECOND},
	{Name: "minute_second", Id: MINUTE_SECOND},
	{Name: "mod", Id: MOD},
	{Name: "mode", Id: MODE},
	{Name: "modify", Id: MODIFY},
	{Name: "modifies", Id: UNUSED},
	{Name: "multilinestring", Id: MULTILINESTRING},
	{Name: "multipoint", Id: MULTIPOINT},
	{Name: "multipolygon", Id: MULTIPOLYGON},
	{Name: "month", Id: MONTH},
	{Name: "name", Id: NAME},
	{Name: "names", Id: NAMES},
	{Name: "natural", Id: NATURAL},
	{Name: "nchar", Id: NCHAR},
	{Name: "next", Id: NEXT},
	{Name: "nested", Id: NESTED},
	{Name: "no", Id: NO},
	{Name: "none", Id: NONE},
	{Name: "not", Id: NOT},
	{Name: "now", Id: NOW},
	{Name: "no_write_to_binlog", Id: NO_WRITE_TO_BINLOG},
	{Name: "nth_value", Id: UNUSED},
	{Name: "ntile", Id: UNUSED},
	{Name: "null", Id: NULL},
	{Name: "numeric", Id: NUMERIC},
	{Name: "of", Id: OF},
	{Name: "off", Id: OFF},
	{Name: "offset", Id: OFFSET},
	{Name: "on", Id: ON},
	{Name: "only", Id: ONLY},
	{Name: "open", Id: OPEN},
	{Name: "optimize", Id: OPTIMIZE},
	{Name: "optimizer_costs", Id: OPTIMIZER_COSTS},
	{Name: "option", Id: OPTION},
	{Name: "optionally", Id: OPTIONALLY},
	{Name: "or", Id: OR},
	{Name: "order", Id: ORDER},
	{Name: "ordinality", Id: ORDINALITY},
	{Name: "out", Id: UNUSED},
	{Name: "outer", Id: OUTER},
	{Name: "outfile", Id: OUTFILE},
	{Name: "over", Id: UNUSED},
	{Name: "overwrite", Id: OVERWRITE},
	{Name: "pack_keys", Id: PACK_KEYS},
	{Name: "parser", Id: PARSER},
	{Name: "partial", Id: PARTIAL},
	{Name: "partition", Id: PARTITION},
	{Name: "partitions", Id: PARTITIONS},
	{Name: "partitioning", Id: PARTITIONING},
	{Name: "password", Id: PASSWORD},
	{Name: "path", Id: PATH},
	{Name: "percent_rank", Id: UNUSED},
	{Name: "plugins", Id: PLUGINS},
	{Name: "point", Id: POINT},
	{Name: "polygon", Id: POLYGON},
	{Name: "precision", Id: UNUSED},
	{Name: "prepare", Id: PREPARE},
	{Name: "primary", Id: PRIMARY},
	{Name: "privileges", Id: PRIVILEGES},
	{Name: "processlist", Id: PROCESSLIST},
	{Name: "procedure", Id: PROCEDURE},
	{Name: "query", Id: QUERY},
	{Name: "range", Id: RANGE},
	{Name: "quarter", Id: QUARTER},
	{Name: "rank", Id: UNUSED},
	{Name: "ratio", Id: RATIO},
	{Name: "read", Id: READ},
	{Name: "reads", Id: UNUSED},
	{Name: "read_write", Id: UNUSED},
	{Name: "real", Id: REAL},
	{Name: "rebuild", Id: REBUILD},
	{Name: "recursive", Id: RECURSIVE},
	{Name: "redundant", Id: REDUNDANT},
	{Name: "references", Id: REFERENCES},
	{Name: "regexp", Id: REGEXP},
	{Name: "relay", Id: RELAY},
	{Name: "release", Id: RELEASE},
	{Name: "remove", Id: REMOVE},
	{Name: "rename", Id: RENAME},
	{Name: "reorganize", Id: REORGANIZE},
	{Name: "repair", Id: REPAIR},
	{Name: "repeat", Id: UNUSED},
	{Name: "repeatable", Id: REPEATABLE},
	{Name: "replace", Id: REPLACE},
	{Name: "require", Id: UNUSED},
	{Name: "resignal", Id: UNUSED},
	{Name: "restrict", Id: RESTRICT},
	{Name: "return", Id: UNUSED},
	{Name: "returning", Id: RETURNING},
	{Name: "retry", Id: RETRY},
	{Name: "revert", Id: REVERT},
	{Name: "revoke", Id: UNUSED},
	{Name: "right", Id: RIGHT},
	{Name: "rlike", Id: REGEXP},
	{Name: "rollback", Id: ROLLBACK},
	{Name: "row", Id: UNUSED},
	{Name: "row_format", Id: ROW_FORMAT},
	{Name: "row_number", Id: UNUSED},
	{Name: "rows", Id: UNUSED},
	{Name: "rtrim", Id: RTRIM},
	{Name: "s3", Id: S3},
	{Name: "savepoint", Id: SAVEPOINT},
	{Name: "schema", Id: SCHEMA},
	{Name: "schemas", Id: SCHEMAS},
	{Name: "second", Id: SECOND},
	{Name: "second_microsecond", Id: SECOND_MICROSECOND},
	{Name: "secondary_engine_attribute", Id: SECONDARY_ENGINE_ATTRIBUTE},
	{Name: "security", Id: SECURITY},
	{Name: "select", Id: SELECT},
	{Name: "sensitive", Id: UNUSED},
	{Name: "separator", Id: SEPARATOR},
	{Name: "sequence", Id: SEQUENCE},
	{Name: "serializable", Id: SERIALIZABLE},
	{Name: "session", Id: SESSION},
	{Name: "set", Id: SET},
	{Name: "share", Id: SHARE},
	{Name: "shared", Id: SHARED},
	{Name: "show", Id: SHOW},
	{Name: "signal", Id: UNUSED},
	{Name: "signed", Id: SIGNED},
	{Name: "simple", Id: SIMPLE},
	{Name: "slow", Id: SLOW},
	{Name: "smallint", Id: SMALLINT},
	{Name: "spatial", Id: SPATIAL},
	{Name: "specific", Id: UNUSED},
	{Name: "sql", Id: SQL},
	{Name: "sqlexception", Id: UNUSED},
	{Name: "sqlstate", Id: UNUSED},
	{Name: "sqlwarning", Id: UNUSED},
	{Name: "sql_big_result", Id: UNUSED},
	{Name: "sql_cache", Id: SQL_CACHE},
	{Name: "sql_calc_found_rows", Id: SQL_CALC_FOUND_ROWS},
	{Name: "sql_no_cache", Id: SQL_NO_CACHE},
	{Name: "sql_small_result", Id: UNUSED},
	{Name: "ssl", Id: UNUSED},
	{Name: "start", Id: START},
	{Name: "starting", Id: STARTING},
	{Name: "stats_auto_recalc", Id: STATS_AUTO_RECALC},
	{Name: "stats_persistent", Id: STATS_PERSISTENT},
	{Name: "stats_sample_pages", Id: STATS_SAMPLE_PAGES},
	{Name: "status", Id: STATUS},
	{Name: "storage", Id: STORAGE},
	{Name: "stored", Id: STORED},
	{Name: "straight_join", Id: STRAIGHT_JOIN},
	{Name: "stream", Id: STREAM},
	{Name: "system", Id: UNUSED},
	{Name: "table", Id: TABLE},
	{Name: "tables", Id: TABLES},
	{Name: "tablespace", Id: TABLESPACE},
	{Name: "temporary", Id: TEMPORARY},
	{Name: "temptable", Id: TEMPTABLE},
	{Name: "terminated", Id: TERMINATED},
	{Name: "text", Id: TEXT},
	{Name: "than", Id: THAN},
	{Name: "then", Id: THEN},
	{Name: "throttle", Id: THROTTLE},
	{Name: "time", Id: TIME},
	{Name: "timestamp", Id: TIMESTAMP},
	{Name: "timestampadd", Id: TIMESTAMPADD},
	{Name: "timestampdiff", Id: TIMESTAMPDIFF},
	{Name: "tinyblob", Id: TINYBLOB},
	{Name: "tinyint", Id: TINYINT},
	{Name: "tinytext", Id: TINYTEXT},
	{Name: "to", Id: TO},
	{Name: "trailing", Id: TRAILING},
	{Name: "transaction", Id: TRANSACTION},
	{Name: "tree", Id: TREE},
	{Name: "traditional", Id: TRADITIONAL},
	{Name: "trigger", Id: TRIGGER},
	{Name: "triggers", Id: TRIGGERS},
	{Name: "true", Id: TRUE},
	{Name: "truncate", Id: TRUNCATE},
	{Name: "trim", Id: TRIM},
	{Name: "uncommitted", Id: UNCOMMITTED},
	{Name: "undefined", Id: UNDEFINED},
	{Name: "undo", Id: UNUSED},
	{Name: "unicode", Id: UNICODE},
	{Name: "union", Id: UNION},
	{Name: "unique", Id: UNIQUE},
	{Name: "unlock", Id: UNLOCK},
	{Name: "unsigned", Id: UNSIGNED},
	{Name: "unthrottle", Id: UNTHROTTLE},
	{Name: "update", Id: UPDATE},
	{Name: "upgrade", Id: UPGRADE},
	{Name: "usage", Id: UNUSED},
	{Name: "use", Id: USE},
	{Name: "user", Id: USER},
	{Name: "user_resources", Id: USER_RESOURCES},
	{Name: "using", Id: USING},
	{Name: "utc_date", Id: UTC_DATE},
	{Name: "utc_time", Id: UTC_TIME},
	{Name: "utc_timestamp", Id: UTC_TIMESTAMP},
	{Name: "validation", Id: VALIDATION},
	{Name: "values", Id: VALUES},
	{Name: "variables", Id: VARIABLES},
	{Name: "varbinary", Id: VARBINARY},
	{Name: "varchar", Id: VARCHAR},
	{Name: "varcharacter", Id: UNUSED},
	{Name: "varying", Id: UNUSED},
	{Name: "vgtid_executed", Id: VGTID_EXECUTED},
	{Name: "virtual", Id: VIRTUAL},
	{Name: "vindex", Id: VINDEX},
	{Name: "vindexes", Id: VINDEXES},
	{Name: "view", Id: VIEW},
	{Name: "vitess", Id: VITESS},
	{Name: "vitess_keyspaces", Id: VITESS_KEYSPACES},
	{Name: "vitess_metadata", Id: VITESS_METADATA},
	{Name: "vitess_migration", Id: VITESS_MIGRATION},
	{Name: "vitess_migrations", Id: VITESS_MIGRATIONS},
	{Name: "vitess_replication_status", Id: VITESS_REPLICATION_STATUS},
	{Name: "vitess_shards", Id: VITESS_SHARDS},
	{Name: "vitess_tablets", Id: VITESS_TABLETS},
	{Name: "vitess_target", Id: VITESS_TARGET},
	{Name: "vitess_throttled_apps", Id: VITESS_THROTTLED_APPS},
	{Name: "vschema", Id: VSCHEMA},
	{Name: "vstream", Id: VSTREAM},
	{Name: "warnings", Id: WARNINGS},
	{Name: "weight_string", Id: WEIGHT_STRING},
	{Name: "when", Id: WHEN},
	{Name: "where", Id: WHERE},
	{Name: "while", Id: UNUSED},
	{Name: "window", Id: UNUSED},
	{Name: "with", Id: WITH},
	{Name: "without", Id: WITHOUT},
	{Name: "work", Id: WORK},
	{Name: "write", Id: WRITE},
	{Name: "visible", Id: VISIBLE},
	{Name: "xor", Id: XOR},
	{Name: "year", Id: YEAR},
	{Name: "year_month", Id: YEAR_MONTH},
	{Name: "zerofill", Id: ZEROFILL},
}

func GetKeywords() []cache.Keyword {
	result := make([]cache.Keyword, len(keywords))
	for i, keyword := range keywords {
		result[i] = cache.Keyword(keyword)
	}
	return result
}

// keywordStrings contains the reverse mapping of token to keyword strings
var keywordStrings = map[int]string{}

func buildCaseInsensitiveTable(keywords []cache.Keyword) *cache.CaseInsensitiveTable {
	table := &cache.CaseInsensitiveTable{
		Hashes: make(map[uint64]cache.Keyword, len(keywords)),
	}

	for _, kw := range keywords {
		hash := cache.Fnv1aIstr(cache.Offset64, kw.Name)
		if _, exists := table.Hashes[hash]; exists {
			panic("collision in caseInsensitiveTable")
		}
		table.Hashes[hash] = kw
	}
	return table
}

func init() {
	for _, kw := range keywords {
		if kw.Id == UNUSED {
			continue
		}
		if kw.Name != strings.ToLower(kw.Name) {
			panic(fmt.Sprintf("keyword %q must be lowercase in table", kw.Name))
		}
		keywordStrings[kw.Id] = kw.Name
	}

	cache.KeywordLookupTable = buildCaseInsensitiveTable(keywords)
}

// KeywordString returns the string corresponding to the given keyword
func KeywordString(id int) string {
	str, ok := keywordStrings[id]
	if !ok {
		return ""
	}
	return str
}
